export const OPEN_SIGNIN_MODAL = 'OPEN_SIGNIN_MODAL';
export const OPEN_SIGNUP_MODAL = 'OPEN_SIGNUP_MODAL';
export const OPEN_ADD_PARCEL_MODAL = 'OPEN_ADD_PARCEL_MODAL';
export const UPDATE_IS_AUTH = 'UPDATE_IS_AUTH';
